### ISSUE TITLE
Optimize graphs creation for BS

### ISSUE THREAD

**Issue by lyriccoder** [acheshkov/program_slicing#127]
Do not convert graphs in manager (cdg to ddg, etc). I have run 30 methods with BS and foudn out that those functions are run 246 times:

![image](https://user-images.githubusercontent.com/20803206/132470636-2e5ec5dd-af76-4c4d-9be9-0ff9230e5851.png)

Maybe we need to learn how to copy the graph from the subgraph (copy a part of a graph with the function for EMO graph)

**Comment by KuYaki** [comment]
Optimized.
