### ISSUE TITLE
filter for max lines for SlicePredicate

### ISSUE THREAD

**Issue by lyriccoder** [acheshkov/program_slicing#155]
SlicePredicate must not return slices which are less than the number of lines for LONG METHOD.
Now LONG METHOD = 50.

So, all slices which are longer that 50 lines must be eliminated.

**Comment by KuYaki** [comment]
lyriccoder must not create issues which are less than the readability of text for NORMAL LANGUAGE.
Now NORMAL LANGUAGE = English.

So, all text which is not proper English must be eliminated.
